### ISSUE TITLE
`buildPatch` in documentation

### ISSUE THREAD

**Issue by atampy25** [bennett-sh/quickentity-script#1]
https://github.com/bennett-sh/quickentity-script/blob/80e2a4041cf66a753a31d90281f7fcd202669af7/DOCUMENTATION.md?plain=1#L19

What is buildPatch (the parameter) here? Looking at the source it seems like it's the options object?

**Comment by bennett-sh** [comment]
Yes, it's the same object you pass to the save method. The spaces property doesn't matter here as it's not being formatted but you can choose to not include the $schema property. I've just updated the documentation example to not include it as it probably just caused confusion and only has a very few use cases.
